Add German translation
ionutbortis/gnome-bedtime-mode pull request #19
Opened 2021-10-02 22:23 UTC by daPhipz

As it says in the title.
Unfortunately, I was unable to find a suitable German translation for two strings - do you maybe have an explanation for me?

2021-10-03 07:43 UTC, ionutbortis requested changes
Great work Philipp!

Thank you so much for investing your time into this!

The overall translation looks really good, please see my review comments for the texts you had your doubts with. 
I might change "Apply Factor" to "Intensity" in the English version so I guess you can safely go with that :smiley:

2021-10-03 07:43 UTC, ionutbortis commented on po/de.po
> +msgstr "orange"
To keep consistency, I think we should start with an upper case letter, "Orange".

2021-10-03 07:43 UTC, ionutbortis commented on po/de.po
> +msgstr ""
Maybe this choice of words could have been better...

I guess you could use "Color Preset and Intensity Factor" or "Color Preset and Intensity" as a reference for the German equivalent.

"Intensity" seems like a better fit instead of "Apply Factor". Oh, well :grimacing:

2021-10-03 07:43 UTC, ionutbortis commented on po/de.po
> +msgstr ""
As I mentioned above, maybe you could use "Color Intensity Factor" or "Color Intensity", whichever seems more appropriate for a German translation.

2021-10-03 22:16 UTC, daPhipz commented
Thanks for the explanations! Everything is clear now.
As far as I am concerned, the translation is ready to merge! :tada:

2021-10-04 06:10 UTC, ionutbortis commented
Thanks, looks good! :smiley: 

I'll ping you later on if there is a need for translations update. I'm thinking of implementing a feature request so there might be 2 new texts for translation.

2021-10-04 06:11 UTC, merged

2021-10-04 09:18 UTC, daPhipz commented
> I'll ping you later on if there is a need for translations update.

Yes, that's a good idea!